name: Daily News Scraper
on:
  schedule:
    # Run every 3 hours from 6:00 to 21:00 (GMT+1)
    # In UTC: 5:00, 8:00, 11:00, 14:00, 17:00, 20:00
    - cron: '0 5,8,11,14,17,20 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run scraper
        run: python scripts/scraper.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_GEMINI_API_KEY: ${{ secrets.GOOGLE_GEMINI_API_KEY }}